version: "3.0"

services:
  web:
    image: node:14
    ports:
      - "3000:3000"
    volumes:
      - "./app:/home/node/app"
    command: sh -c "
      cd /home/node/app &&
      npm install &&
      npm start"